/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.petete.dev.demo.async.process.api;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import it.petete.dev.demo.async.process.model.CommonErrorDTO;
import it.petete.dev.demo.async.process.model.EntityDto;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-02T15:28:17.541+02:00")

@Api(value = "entity", description = "the SyncAsync API")
public interface SyncAsyncApi {
    
    @ApiOperation(
			   value = "Search by code (Sync Vresion)", notes = "Returns the detail of Entity by code provided as query parameter. (Sync Vresion)",
			   response = EntityDto.class, tags = { "Entity", })
    @ApiResponses(value = {
			   @ApiResponse(code = 200, message = "Ok", response = EntityDto.class),
			   @ApiResponse(code = 400, message = "Bad Request", response = CommonErrorDTO.class),
			   @ApiResponse(code = 404, message = "Not Found", response = CommonErrorDTO.class) })
    
    @RequestMapping(value = "/sync/entity/{code}", produces = { "application/json" }, method = RequestMethod.GET)
    default ResponseEntity<?> getEntityByCodeSync(
			   @ApiParam(value = "Numeric code of the Entity", required = true) @PathVariable("code") final String code,
			   @ApiParam(value = "Identifier of invoke request message. If not defined, will be generated by MiSe as UUID.") @RequestHeader(value = "X-CORRELATION-ID", required = false) final String X_CORRELATION_ID) {
	 // do some magic!
	 return new ResponseEntity<EntityDto>(HttpStatus.OK);
    }
    
    @ApiOperation(
			   value = "Search by code (Async Vresion)", notes = "Returns the detail of Entity by code provided as query parameter. (Async Vresion)",
			   response = EntityDto.class, tags = { "Entity", })
    @ApiResponses(value = {
			   @ApiResponse(code = 200, message = "Ok", response = EntityDto.class),
			   @ApiResponse(code = 400, message = "Bad Request", response = CommonErrorDTO.class),
			   @ApiResponse(code = 404, message = "Not Found", response = CommonErrorDTO.class) })
    
    @RequestMapping(value = "/async/entity/{code}", produces = { "application/json" }, method = RequestMethod.GET)
    default ResponseEntity<?> getEntityByCodeAsync(
			   @ApiParam(value = "Numeric code of the Entity", required = true) @PathVariable("code") final String code,
			   @ApiParam(value = "Identifier of invoke request message. If not defined, will be generated by MiSe as UUID.") @RequestHeader(value = "X-CORRELATION-ID", required = false) final String X_CORRELATION_ID) {
	 // do some magic!
	 return new ResponseEntity<EntityDto>(HttpStatus.OK);
    }
    
}
